# Generated by Django 4.2.3 on 2023-07-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_meal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='lunch',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
