# Generated by Django 4.2.3 on 2023-07-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_meal_breakfast_remove_meal_dinner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='meal_name',
        ),
        migrations.AddField(
            model_name='meal',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
