# Generated by Django 4.2.3 on 2023-07-29 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_dailymeals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymeals',
            name='meals',
        ),
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=100)),
                ('daily_meals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.dailymeals')),
            ],
        ),
    ]
