# Generated by Django 4.2.3 on 2023-07-29 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0011_alter_mealentry_daily_meals_delete_dailymeals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealentry',
            name='daily_meals',
        ),
        migrations.AddField(
            model_name='mealentry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
