# Generated by Django 4.2.3 on 2023-07-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_mealentry_daily_meals_mealentry_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MealEntry',
        ),
    ]
