# Generated by Django 4.2.4 on 2023-08-25 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_workoutcontainer_workout_container'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='container',
        ),
        migrations.DeleteModel(
            name='WorkoutContainer',
        ),
    ]
